### ISSUE TITLE
Integrate the Actions compromise presented at January WebRTC interim

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-handle#6] opened 2022-02-11 17:06 UTC
We agreed to proceed with the API presented at the [WebRTC interim in January](https://www.w3.org/2022/01/18-webrtc-minutes.html#t06), which adds the important [Actions](https://docs.google.com/presentation/d/1j-RkOfgXPWxi8odvTLWqa_VR2QZ6-7sgLvKxOptw_Lk/edit#slide=id.g10da1807a11_11_47) component, which through standardization won’t limit this critical cross-app functionality to web properties owned by the same corporation.

The [Actions](https://www.w3.org/2022/01/18-webrtc-minutes.html#t06) presented are the template rudimentary “next", “previous", “first", and “last” ones needed to advance slides from a VC (that is: to drive a tab-captured generic web presentation from another generic VC tab), as an addition to the spec's “identification” section (which lets properties partner to provide the same and more through tight integration across specific products).

This is important for scope, and a blocker for CfA.

**Comment by eladalon1983** [comment] 2022-02-14 21:24
It is important to accurately portray agreements. What we agreed to do was **offer the WG** something along the general lines of Actions, and that I did - I came up with a concrete proposal, I presented it to the Working Group, and I debated its merits at length with @youennf. The debate started [here](https://github.com/w3c/mediacapture-screen-share/issues/166#issuecomment-1012503381), in the comment from Jan 14. Please contrast my engagement and Youenn's with that of other participants in the debate. I think my commitment Actions has been very high.

Where do we stand now?
* Only one member of the WG is expressing strong interest in specifying Actions.
* Only one member of the WG is of the opinion that Identity and Actions need to occupy the same document.
* Exactly zero members of the WG have mentioned they plan to implement Actions in the foreseeable future.
* There is no consensus over the shape of Actions (see aofrementioned debate with @youennf).
* There is rough consensus over the shape of Identity.
* There is wide support for Identity and we have partners who are clamoring for it. (Google, Microsoft, RingCentral, Jitsi, Zoom, Citrix.)

It serves nobody to block Identity on something entirely distinct and without consensus. But you're welcome to send a PR, debate it with Youenn, and get it merged. If this document is adopted by the W3C, we can follow the official process.

**Comment by alvestrand** [comment] 2022-02-14 21:50
As I said in January, I am in favor of having Capture Handle and Actions as two separate documents.
In addition to what Elad says - I believe that Actions, if it finds interest with Web developers, has a lot wider applicability than Capture Handle, and should not be tied to it.
(I also think that Actions are out of scope for WebRTC, and should be pursued in WICG or WebApps, but we can debate the merits of that argument somewhat separately from the debate about integrating it in the Capture Handle document.)

**Comment by jan-ivar** [comment] 2022-02-17 14:19
It is disappointing to see us backing away from compromises reached at the January meeting.

I think it's valid concern that the final shape of actions are not clear, and would be satisfied by including a statement that includes their consideration, since they're a mitigation to concerns raised with the Identity part of this document. This should allow us to keep refining the API shape and discuss whether this should be one document or two. Anything less is not a compromise I fear.

**Comment by jan-ivar** [comment] 2022-02-17 22:34
> ... it's an attempt to mandate support for loosely coupled applications when all the use cases we have been presented so far by Web developers are for the abilitiy to support tightly coupled applications).

@alvestrand Here's a web developer from the public-webrtc mailing list [last June](https://lists.w3.org/Archives/Public/public-webrtc/2021Jun/0025.html):

_"Hi Elad,_

_I find this API really interesting and I can understand the value for google and other service providers. However, it is unclear what is the benefit for the rest of the community. Let me explain my concerns._

_Given that the method are opt-in, I foresee that only the web sites interested in being captured will ever use this API, and given that the the web sites can set the domains that will be allowed to receive that information, it is not unreasonable to think that they will only allow for the same company VC products._

_So my worries are that we will end up having an API that will be only enabled in google docs to be able to expose information to google meet, and in microsoft 360 to expose information to microsoft teams, and they will be able to provide a much better presentation experience than the rest of VC services. I am not saying that these are Google or Microsoft intentions, but that is a more than feasible possibility._

_I understand the value of an API like that, but I think it should be a benefit for all, not just for the ones that control both the content and the conferencing services. I really hope that the API can be modified so this can happen._

_Best regards
Sergio"_

**Comment by eladalon1983** [comment] 2022-02-20 11:55
> Thanks, here's the PR you requested #15. PTAL. I've cc'ed @youennf.

Thanks. I will indeed take a look.

> My understanding from the January meeting was that in the interest of progress, everyone was willing to adopt and iterate from what was presented at the January meeting.

I do not recall @youennf agreeing to that. Can he either comment here saying as much, or can you point out his agreement elsewhere?


By the way, let's remember what I agreed to. [Quoting myself](https://github.com/w3c/mediacapture-screen-share/issues/166#issuecomment-1013161492):
> There are two core issues addressed in this thread, which I'll call "identity" ([original proposal](https://wicg.github.io/capture-handle/)) and "actions" ([additional mechanisms](https://github.com/w3c/mediacapture-screen-share/issues/166#issuecomment-1012503381)). I also **prefer** splitting the work, but I **tentatively propose** addressing both issues together as an attempt to reach a compromise with @jan-ivar. To avoid risking misrepresenting his position, I'd like to ask @jan-ivar to explain why he thinks the two should be combined.

This "tentative proposal" was intended to expedite things and help build consensus. It's usually much harder to reach a compromise on multiple topics than on one. The [thread with Youenn](https://github.com/w3c/mediacapture-screen-share/issues/166#issuecomment-1012503381) starting January 13 proves that Actions is **not** an exception to this rule. I no longer think the trade-off presented by such a proposal is favorable.

**Comment by eladalon1983** [comment] 2022-03-15 16:21
@jan-ivar, IIANM this is all now integrated, so I'm closing. If I'm mistaken, do please reopen.

**Closed by eladalon1983** 2022-03-15 16:21 UTC
